#spring:
 # application:
  #  name: ms-cliente-service
  #profiles:
   # active: development
  #config:
   # import: optional:configserver:http://root:123456@localhost:2000
spring:
  application:
    name: ms-cliente-service
  profiles:
    active: development

spring.config.import: optional:configserver:http://root:123456@localhost:2000