server:
  port: 2000
spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hokjose/eco_dan_joss.git
          searchPaths: config-data
          default-label: main
  security:
    user:
      name: root
      password: 123456