server:
  #port: 2021
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: ms-cliente-service
  datasource:
    url: jdbc:postgresql://localhost:5432/eco-cliente
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:2020/eureka
      defaultZone: ${EUREKA_URI:http://localhost:2020/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}