server:
  port: 2999

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:2020/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-venta-service
              uri: lb://ms-venta-service
              predicates:
                - Path=/venta/**, /detalleventa/**, /tipoventa/**, /formapago/**
              filters:
                - AuthFilter
          
            - id: ms-cliente-service
              uri: lb://ms-cliente-service
              predicates:
                - Path=/cliente/**
              filters:
                - AuthFilter
    
            - id: ms-producto-service
              uri: lb://ms-producto-service
              predicates:
                - Path=/producto/**, /marca/**, /genero/**, /color/**
              filters:
                - AuthFilter
              
            - id: ms-auth-service
              uri: lb://ms-auth-service
              predicates:
                - Path=/auth/**
          

          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:4200"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                allow-credentials: true
                max-age: 3600
